"""Build offline pronunciation and licensed bilingual examples; no runtime network."""
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORK = ROOT / 'scripts' / 'work'
rows = json.loads((ROOT / 'data' / 'vocabulary.js').read_text('utf-8').split('module.exports=')[1].rstrip(';\n\r'))
ALIASES = {'airconditioning': 'air conditioning', 'organisation/-z ation': 'organization',
           'theatre/-ter': 'theater', 'judg(e)ment': 'judgment', 'catalog(ue)': 'catalog',
           'program(me)': 'program', 'fantastic(al)': 'fantastic', 'fulfil(l)': 'fulfill',
           'instal(l)': 'install', 'wag(g)on': 'wagon', 'practise/-ice': 'practice'}
PHONETICS = {
    'affordable': 'əˈfɔːrdəbəl', 'conservative': 'kənˈsɜːrvətɪv', 'owing to': 'ˈoʊɪŋ tuː',
    'air conditioning': 'ˈer kənˌdɪʃənɪŋ', 'core': 'kɔːr', 'grown-up': 'ˈɡroʊn ʌp',
    'Internet': 'ˈɪntərnet', 'ought to': 'ˈɔːt tuː', 'pole': 'poʊl', 'polish': 'ˈpɑːlɪʃ',
    'proceedings': 'prəˈsiːdɪŋz', 'so-called': 'ˌsoʊ ˈkɔːld', 'well-known': 'ˌwel ˈnoʊn',
}

def headword(word):
    if word in ALIASES:
        return ALIASES[word]
    word = re.sub(r'\(u\)', '', word)
    word = re.sub(r'\(([a-z]+)\)', r'\1', word)
    word = word.split('/')[0].strip()
    return word

heads = {headword(r[3]) for r in rows}
dictionary = {}
with (WORK / 'ecdict.csv').open(encoding='utf-8', newline='') as file:
    for entry in csv.DictReader(file):
        if entry['word'] in heads:
            dictionary[entry['word']] = entry

forms = {}
for head in heads:
    variants = {head, head + 's', head + 'es', head + 'd', head + 'ed', head + 'ing'}
    for exchange in dictionary.get(head, {}).get('exchange', '').split('/'):
        if ':' in exchange:
            tag, value = exchange.split(':', 1)
            if tag in {'p', 'd', 'i', '3', 's', 'r', 't'}:
                variants.add(value)
    for form in variants:
        forms.setdefault(form, set()).add(head)

candidates = {}
for line in (WORK / 'tatoeba' / 'cmn.txt').read_text('utf-8').splitlines():
    en, zh, credit = line.split('\t')
    if not 5 <= len(en.split()) <= 20 or len(en) > 145:
        continue
    tokens = re.findall(r"[a-z]+(?:['-][a-z]+)*", en.lower())
    matches = set()
    for size in (1, 2):
        for i in range(len(tokens) - size + 1):
            matches.update(forms.get(' '.join(tokens[i:i + size]), set()))
    for head in matches:
        candidates.setdefault(head, []).append((en, zh, credit))

manual_path = ROOT / 'data' / 'authored-examples.tsv'
manual = {}
if manual_path.exists():
    for line in manual_path.read_text('utf-8').splitlines():
        if not line or line.startswith('#'):
            continue
        head, en, zh = line.split('\t')
        for key in head.split('|'):
            manual[key] = (en, zh, 'LexiLoop 编写')

content, missing, missing_ipa = {}, [], []
manifest = []
audio_heads = {}
for i, row in enumerate(rows):
    word_id = '-'.join(map(str, row[:3]))
    head = headword(row[3])
    entry = dictionary.get(head, {})
    phone = PHONETICS.get(head) or entry.get('phonetic', '')
    if not phone:
        missing_ipa.append((word_id, head))
    meanings = [m.strip() for m in re.split('[；;，]', row[4]) if len(m.strip()) >= 2]
    def score(candidate):
        en, zh, credit = candidate
        overlap = max([len(m) for m in meanings if m in zh] or [0])
        return (overlap > 0, overlap, -abs(len(en.split()) - 9), -len(en))
    options = candidates.get(head, [])
    selected = manual.get(head) or (max(options, key=score) if options else None)
    if head not in audio_heads:
        audio_index = len(audio_heads)
        package = 'speech%02d' % (audio_index // 220 + 1)
        audio_heads[head] = (package, '/%s/%s.mp3' % (package, word_id))
        manifest.append({'id': word_id, 'word': head, 'package': package, 'path': audio_heads[head][1]})
    package, audio = audio_heads[head]
    extra = {'spokenWord': head, 'ipa': '/' + phone.strip('/') + '/' if phone else '', 'audio': audio, 'audioPackage': package}
    if selected:
        extra.update(example=selected[0], translation=selected[1], exampleCredit=selected[2])
    else:
        missing.append((head, row[4]))
    content[word_id] = extra

(ROOT / 'data' / 'learning-content.js').write_text('// Generated by scripts/build-learning-content.py\nmodule.exports = ' + json.dumps(content, ensure_ascii=False, separators=(',', ':')) + ';\n', 'utf-8')
(WORK / 'audio-manifest.json').write_text(json.dumps(manifest, ensure_ascii=False), 'utf-8')
(WORK / 'missing-examples.json').write_text(json.dumps(dict(missing), ensure_ascii=False, indent=2), 'utf-8')
print(json.dumps({'words': len(content), 'examples': len(content)-len(missing), 'missing': len(set(h for h, _ in missing)), 'missingIPA': missing_ipa, 'audio': len(manifest)}, ensure_ascii=False))
